// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using task_api.Migrations;

#nullable disable

namespace taskapi.Migrations
{
    [DbContext(typeof(taskDbContext))]
    partial class taskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("task_api.Models.task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.ToTable("task");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            Completed = false,
                            Title = "greeting"
                        },
                        new
                        {
                            TaskId = 2,
                            Completed = true,
                            Title = "go to school"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
